# Generated by Django 3.2.15 on 2022-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('jobID', models.CharField(max_length=140, primary_key=True)),
                ('resourceId', models.CharField(max_length=140, null=True)),
                ('partID', models.CharField(max_length=140, null=True)),
                ('jobInputDate', models.DateTimeField(null=True)),
                ('deadlineDate', models.DateTimeField(null=True)),
                ('productionStart', models.DateTimeField(null=True)),
                ('productionEnd', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ('jobID',),
            },
        ),
    ]
