# Generated by Django 3.2.15 on 2022-09-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineId', models.CharField(max_length=140, null=True)),
                ('percentageOccupancy', models.CharField(max_length=140, null=True)),
                ('maxDuration', models.CharField(max_length=140, null=True)),
            ],
        ),
    ]
